In [1]:
import numpy as np

In [6]:
nrows = 5
ncolums = 6

nrows = 10
ncolums = 12

npixels = nrows * ncolums
pixel_index = np.arange(npixels).reshape((nrows, ncolums))

# reverse every other row to allow for the ordering of the lights
pixel_index[1::2] = pixel_index[1::2, ::-1]

if nrows > 5:
    # Reverse all rows after the 5th row (index 5 onward)
    pixel_index[5:] = pixel_index[5:, ::-1]

print(pixel_index)


print(pixel_index[4,5])

[[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 23  22  21  20  19  18  17  16  15  14  13  12]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 47  46  45  44  43  42  41  40  39  38  37  36]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71]
 [ 83  82  81  80  79  78  77  76  75  74  73  72]
 [ 84  85  86  87  88  89  90  91  92  93  94  95]
 [107 106 105 104 103 102 101 100  99  98  97  96]
 [108 109 110 111 112 113 114 115 116 117 118 119]]
53
